export const FETCH_WEATHER_FORECAST_START = 'FETCH_WEATHER_FORECAST_START';
export const FETCH_WEATHER_FORECAST_SUCCESS = 'FETCH_WEATHER_FORECAST_SUCCESS';
export const FETCH_WEATHER_FORECAST_FAILURE = 'FETCH_WEATHER_FORECAST_FAILURE';
export const SET_TEMPERATURE_UNITS = 'SET_TEMPERATURE_UNITS';
